In [1]:
import os

for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/datasets/asaniczka/1-3m-linkedin-jobs-and-skills-2024/job_summary.csv
/kaggle/input/datasets/asaniczka/1-3m-linkedin-jobs-and-skills-2024/job_skills.csv
/kaggle/input/datasets/asaniczka/1-3m-linkedin-jobs-and-skills-2024/linkedin_job_postings.csv

In [2]:
import pandas as pd

df = pd.read_csv('/kaggle/input/datasets/asaniczka/1-3m-linkedin-jobs-and-skills-2024/linkedin_job_postings.csv', nrows=100000)

df.head()

,job_link,last_processed_time,got_summary,got_ner,is_being_worked,job_title,company,job_location,first_seen,search_city,search_country,search_position,job_level,job_type
0,https://www.linkedin.com/jobs/view/account-exe...,2024-01-21 07:12:29.00256+00,t,t,f,Account Executive - Dispensing (NorCal/Norther...,BD,"San Diego, CA",2024-01-15,Coronado,United States,Color Maker,Mid senior,Onsite
1,https://www.linkedin.com/jobs/view/registered-...,2024-01-21 07:39:58.88137+00,t,t,f,Registered Nurse - RN Care Manager,Trinity Health MI,"Norton Shores, MI",2024-01-14,Grand Haven,United States,Director Nursing Service,Mid senior,Onsite
2,https://www.linkedin.com/jobs/view/restaurant-...,2024-01-21 07:40:00.251126+00,t,t,f,RESTAURANT SUPERVISOR - THE FORKLIFT,Wasatch Adaptive Sports,"Sandy, UT",2024-01-14,Tooele,United States,Stand-In,Mid senior,Onsite
3,https://www.linkedin.com/jobs/view/independent...,2024-01-21 07:40:00.308133+00,t,t,f,Independent Real Estate Agent,Howard Hanna | Rand Realty,"Englewood Cliffs, NJ",2024-01-16,Pinehurst,United States,Real-Estate Clerk,Mid senior,Onsite
4,https://www.linkedin.com/jobs/view/group-unit-...,2024-01-19 09:45:09.215838+00,f,f,f,Group/Unit Supervisor (Systems Support Manager...,"IRS, Office of Chief Counsel","Chamblee, GA",2024-01-17,Gadsden,United States,Supervisor Travel-Information Center,Mid senior,Onsite

In [3]:
df['job_title'] = df['job_title'].astype(str)

df_filtered = df[df['job_title'].str.contains('Data Analyst', case=False, na=False)]

df_filtered.shape

(87, 14)

In [4]:
df['job_title'] = df['job_title'].astype(str)

df_filtered = df[df['job_title'].str.contains('Data Analyst', case=False, na=False)]

df_filtered.shape

(87, 14)

In [5]:
print(df.columns)

Index(['job_link', 'last_processed_time', 'got_summary', 'got_ner',
       'is_being_worked', 'job_title', 'company', 'job_location', 'first_seen',
       'search_city', 'search_country', 'search_position', 'job_level',
       'job_type'],
      dtype='object')

In [6]:
skills = pd.read_csv('/kaggle/input/datasets/asaniczka/1-3m-linkedin-jobs-and-skills-2024/job_skills.csv')

merged = pd.merge(df_filtered, skills, on='job_link')

merged.head()

,job_link,last_processed_time,got_summary,got_ner,is_being_worked,job_title,company,job_location,first_seen,search_city,search_country,search_position,job_level,job_type,job_skills
0,https://www.linkedin.com/jobs/view/senior-fina...,2024-01-21 07:14:50.991803+00,t,t,f,Senior Financial Data Analyst,The Walt Disney Company,"Lake Buena Vista, FL",2024-01-15,Avondale,United States,Budget Officer,Mid senior,Onsite,"Problem solving, Data analysis, Predictive ana..."
1,https://www.linkedin.com/jobs/view/sr-workforc...,2024-01-21 07:15:01.601597+00,t,t,f,Sr. Workforce Management Data Analyst,"Wisemen Multimedia, LLC","Atlanta, GA",2024-01-13,Stockbridge,United States,Management Analyst,Mid senior,Onsite,"SQL, Database Administration, Advanced Statist..."
2,https://ca.linkedin.com/jobs/view/data-analyst...,2024-01-21 00:27:40.684771+00,t,t,f,Data Analyst Part Time,Toyandsons,"Waterloo, Ontario, Canada",2024-01-14,Stratford,Canada,Data Entry Clerk,Mid senior,Onsite,"Data Analysis, Data Visualization, Statistical..."
3,https://www.linkedin.com/jobs/view/contractor-...,2024-01-21 07:16:15.96147+00,t,t,f,Contractor - Epic Clarity Data Analyst - Reven...,Deloitte,"Mississippi, United States",2024-01-14,Magnolia,United States,Data Entry Clerk,Mid senior,Onsite,"Revenue Cycle, Healthcare Data Analysis, Data ..."
4,https://www.linkedin.com/jobs/view/vcp-design-...,2024-01-21 08:02:01.538039+00,t,t,f,VCP Design to Value Project Manager and Data A...,GE HealthCare,"Waukesha, WI",2024-01-14,Waterford,United States,Data Entry Clerk,Mid senior,Onsite,"Variable Cost Productivity, Data Analytics, Co..."

In [7]:
all_skills = merged['job_skills'].str.split(',').explode()

top_skills = all_skills.value_counts().head(10)

top_skills

job_skills
 SQL                   47
 Python                39
 Data Visualization    34
 R                     31
 Tableau               30
Data Analysis          28
 Communication         21
 Reporting             19
 Data Analysis         17
 Project Management    17
Name: count, dtype: int64

In [8]:
print(df_filtered.columns)

Index(['job_link', 'last_processed_time', 'got_summary', 'got_ner',
       'is_being_worked', 'job_title', 'company', 'job_location', 'first_seen',
       'search_city', 'search_country', 'search_position', 'job_level',
       'job_type'],
      dtype='object')

In [9]:
df_filtered['job_location'].value_counts().head(10)

job_location
Washington, DC                       5
New York, NY                         5
Mountain View, CA                    4
Cupertino, CA                        3
Los Angeles, CA                      2
California, United States            2
Dallas, TX                           2
Georgia, United States               1
Awsworth, England, United Kingdom    1
Waukesha, WI                         1
Name: count, dtype: int64

In [10]:
all_skills = merged['job_skills'].str.split(',').explode()

top_skills = all_skills.value_counts().head(10)

top_skills

job_skills
 SQL                   47
 Python                39
 Data Visualization    34
 R                     31
 Tableau               30
Data Analysis          28
 Communication         21
 Reporting             19
 Data Analysis         17
 Project Management    17
Name: count, dtype: int64

In [11]:
skills = pd.read_csv('/kaggle/input/datasets/asaniczka/1-3m-linkedin-jobs-and-skills-2024/job_skills.csv')

merged = pd.merge(df_filtered, skills, on='job_link')

merged.head()

,job_link,last_processed_time,got_summary,got_ner,is_being_worked,job_title,company,job_location,first_seen,search_city,search_country,search_position,job_level,job_type,job_skills
0,https://www.linkedin.com/jobs/view/senior-fina...,2024-01-21 07:14:50.991803+00,t,t,f,Senior Financial Data Analyst,The Walt Disney Company,"Lake Buena Vista, FL",2024-01-15,Avondale,United States,Budget Officer,Mid senior,Onsite,"Problem solving, Data analysis, Predictive ana..."
1,https://www.linkedin.com/jobs/view/sr-workforc...,2024-01-21 07:15:01.601597+00,t,t,f,Sr. Workforce Management Data Analyst,"Wisemen Multimedia, LLC","Atlanta, GA",2024-01-13,Stockbridge,United States,Management Analyst,Mid senior,Onsite,"SQL, Database Administration, Advanced Statist..."
2,https://ca.linkedin.com/jobs/view/data-analyst...,2024-01-21 00:27:40.684771+00,t,t,f,Data Analyst Part Time,Toyandsons,"Waterloo, Ontario, Canada",2024-01-14,Stratford,Canada,Data Entry Clerk,Mid senior,Onsite,"Data Analysis, Data Visualization, Statistical..."
3,https://www.linkedin.com/jobs/view/contractor-...,2024-01-21 07:16:15.96147+00,t,t,f,Contractor - Epic Clarity Data Analyst - Reven...,Deloitte,"Mississippi, United States",2024-01-14,Magnolia,United States,Data Entry Clerk,Mid senior,Onsite,"Revenue Cycle, Healthcare Data Analysis, Data ..."
4,https://www.linkedin.com/jobs/view/vcp-design-...,2024-01-21 08:02:01.538039+00,t,t,f,VCP Design to Value Project Manager and Data A...,GE HealthCare,"Waukesha, WI",2024-01-14,Waterford,United States,Data Entry Clerk,Mid senior,Onsite,"Variable Cost Productivity, Data Analytics, Co..."

In [12]:
merged.to_csv('final_project_data.csv', index=False)